base: ../default.yaml

experiment:
  name: manual_feature_concat
  dataset: Coffee
  representations: [GAF, MTF, RP, STFT]

model:
  name: AdaptiveFusionCNN
  fusion: feature_concat
  feature_dim: 128
  dropout: 0.3
